import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import classNames from 'classnames';
import { ModalProvider } from '@/components/Modal/ModalContext'
import { AuthProvider } from '@/lib/contexts/AuthContext'
import { DialogProvider } from '@/components/Dialog/Context';

const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="default" suppressHydrationWarning={true} className={classNames(inter.className)}>
      <AuthProvider>
        <ModalProvider>
          <DialogProvider>
            <body suppressHydrationWarning={true} className='h-screen w-screen'>{children}</body>
          </DialogProvider>
        </ModalProvider>
      </AuthProvider>
    </html>
  )
}
