import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import classNames from 'classnames'

const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="default" suppressHydrationWarning={true} className={inter.className}>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
