import '@/styles/globals.css'
import localFont from 'next/font/local'
import classNames from 'classnames'

const helvetica = localFont({
  src: [
    {
      path: '../styles/fonts/HelveticaNeueUltraLight.otf',
      weight: '100',
    },
    {
      path: '../styles/fonts/HelveticaNeueLight.otf',
      weight: '300'
    },
    {
      path: '../styles/fonts/HelveticaNeueRoman.otf',
      weight: '400'
    },
    {
      path: '../styles/fonts/HelveticaNeueMedium.otf',
      weight: '500'
    },
    {
      path: '../styles/fonts/HelveticaNeueBold.otf',
      weight: '700'
    },
    {
      path: '../styles/fonts/HelveticaNeueHeavy.otf',
      weight: '900'
    }
  ],
  variable: '--font-family-sans',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="default" suppressHydrationWarning={true} className={classNames(helvetica.variable, 'font-sans')}>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
