import '@/styles/globals.css'
import Navbar from '@/components/Navbar'
import classNames from 'classnames'
import { Inter } from 'next/font/google'
import Banner from '@/components/Banner'
import Footer from '@/components/Footer'
import { ModalProvider } from '@/components/Modal/ModalContext'
import { AuthProvider } from '@/lib/contexts/AuthContext'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="default" suppressHydrationWarning={true} className={classNames(inter.className)}>
      <AuthProvider>
        <ModalProvider>
          <body suppressHydrationWarning={true}>
            <Navbar/>
            <Banner/>
            {children}
            <Footer />
          </body>
          </ModalProvider>
        </AuthProvider>
    </html>
  )
}
