import '@/styles/globals.css'
import Navbar from '@/components/Navbar'
import classNames from 'classnames'
import { Inter } from 'next/font/google'
import Banner from '@/components/Banner'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="default" suppressHydrationWarning={true} className={classNames(inter.className)}>
      <body suppressHydrationWarning={true}>
        <Navbar/>
        <Banner/>
        {children}
        <Footer />
      </body>
    </html>
  )
}
